### ISSUE TITLE
So how would i make the bot give me correct answers?

### ISSUE THREAD

**Issue by Zein-4** [ecc521/gimkit-bot#12]

**Comment by ecc521** [comment]
I'm confused about what you are asking. Is the bot not functioning, or are you asking how you can see what the correct answer was that the bot picked?

**Comment by Zein-4** [comment]
> I'm confused about what you are asking. Is the bot not functioning, or are you asking how you can see what the correct answer was that the bot picked?

So basically, I want to know how I can get the bot to pick the correct answers, because so far when I would press ‘s’ it would pick a random answer not the correct one. How can I make it so that i only get correct answers?

**Comment by ecc521** [comment]
Currently the bot will guess a random answer, click show correct answer to find the correct answer (if it guessed wrong), and will remember the correct answer so it never misses the same question again.

**Comment by ecc521** [comment]
If you want a mode where you answer the questions, then once you have answered them all right, the bot takes over, I'll be happy to merge a PR.

**Comment by Zein-4** [comment]
> If you want a mode where you answer the questions, then once you have answered them all right, the bot takes over, I'll be happy to merge a

> Currently the bot will guess a random answer, click show correct answer to find the correct answer (if it guessed wrong), and will remember the correct answer so it never misses the same question again.

Ahhhh so if the quiz has 50 questions then it will take ages to get the bot to answer them correctly

**Comment by Zein-4** [comment]
And no need for the other thing

**Comment by ecc521** [comment]
Yep. Now if you happen to have the same questions across multiple games, you can copy the answers from one game to the next, but that's a bit complicated.

**Comment by ecc521** [comment]
Since the bot answers around 1 question per second and GimKit shows all questions once before repeating, you can expect the bot to take a little while to get started.
