### ISSUE TITLE
Cheating detected

### ISSUE THREAD

**Issue by ScurySnek2** [ecc521/gimkit-bot#13]
![image](https://user-images.githubusercontent.com/64798216/80989104-50c1dc80-8de9-11ea-91ba-632d29fdb485.png)

When ran on firefox, it does not answer any questions, and after about 30 seconds it quits and gives a screen that says cheating is detected

**Comment by ecc521** [comment]
Duplicate of https://github.com/ecc521/gimkit-bot/issues/8

**Comment by ecc521** [comment]
GimKit kicked you because it detected you answering questions extremely quickly, not because of the bot. This rate limiting often leads to human players getting kicked too, and is currently not handled by the bot.
