### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ChaosPyro** [ecc521/gimkit-bot#19]
whenever I press S it says some functions are undefined.

**Comment by ecc521** [comment]
Haven't attempted to reproduce it, however it shouldn't be that hard to fix. Seems like a function is not defined in scope. PRs are accepted.

**Comment by EnderTunes** [comment]
still doesn't work. I paste it in, i don't get any errors, but the 3 pronged bar at the top blurs a bunch of time and there is lots of sounds. (when i press s)

**Comment by Jeremiah-S** [comment]
Error displays:
ncaught TypeError: Cannot read property 'clientX' of undefined
    at Object.start (static/js/5.6de97fb2.chunk.js:2)
    at static/js/5.6de97fb2.chunk.js:2
    at static/js/5.6de97fb2.chunk.js:2
    at Object.u (4.68521c22.chunk.js:2)
    at h (4.68521c22.chunk.js:2)
    at 4.68521c22.chunk.js:2
    at v (4.68521c22.chunk.js:2)
    at at (4.68521c22.chunk.js:2)
    at ot (4.68521c22.chunk.js:2)
    at ut (4.68521c22.chunk.js:2)
(anonymous) @ static/js/5.6de97fb2.chunk.js:2
(anonymous) @ static/js/5.6de97fb2.chunk.js:2
(anonymous) @ static/js/5.6de97fb2.chunk.js:2
u @ 4.68521c22.chunk.js:2
h @ 4.68521c22.chunk.js:2
(anonymous) @ 4.68521c22.chunk.js:2
v @ 4.68521c22.chunk.js:2
at @ 4.68521c22.chunk.js:2
ot @ 4.68521c22.chunk.js:2
ut @ 4.68521c22.chunk.js:2
ht @ 4.68521c22.chunk.js:2
N @ 4.68521c22.chunk.js:2
I @ 4.68521c22.chunk.js:2
Jt @ 4.68521c22.chunk.js:2
Xt @ 4.68521c22.chunk.js:2
t.unstable_runWithPriority @ 4.68521c22.chunk.js:2
qo @ 4.68521c22.chunk.js:2
z @ 4.68521c22.chunk.js:2
Yt @ 4.68521c22.chunk.js:2
(anonymous)
clickElement
transporter.toQuestion
answerQuestion
startAnswering
(anonymous)
2(unknown) Uncaught (in promise) TypeError: localGetEventListeners is not a function
    at answerQuestion (<anonymous>:95:9)
    at startAnswering (<anonymous>:193:19)
    at <anonymous>:207:13

**Comment by ecc521** [comment]
@Jeremiah-S: If you are not using Chrome, or are using a mobile version of it. you will get that error.

**Comment by TheDarkScripter** [comment]
Your chrome is outdated bc is works for me

**Comment by Jeremiah-S** [comment]
Hrmm. That probably was the case.
I had an available update that was not pushed.
Jeremiah

**Comment by Jeremiah-S** [comment]
That was not the problem.
still receiving the same error(s).

**Comment by YodaLightsabr** [comment]
I have the same errors. ClientX not being defined isn't an error with this script though, it's the getEventListeners function.

**Comment by YodaLightsabr** [comment]
Ah! I figured it out. You have to paste the script *right* when the page loads. GimKit tries to combat bots by setting that function to `undefined`, but you have to beat them to it and set it before the game starts up.

**Comment by ecc521** [comment]
Interesting. getEventListeners is [part of the DevTools API](https://developers.google.com/web/tools/chrome-devtools/console/utilities) - I didn't think pages were able to access it - you sure they can see it when DevTools is open? I certainly don't think they can access it with DevTools closed.

Unless GimKit is hooking something up to a resize event listener, etc, you should be able to simply open DevTools AFTER the page loads, instead of loading the page with DevTools open (not sure which way you did it). 

Or you can always use the request override thing to insert the bot at the very start - I've never figured out how to use that DevTools feature cleanly.
